### ISSUE TITLE
Reduced Solfec output for Solfec viewer

### ISSUE THREAD

**Issue by bencannell** [parmes/solfec#79]
Hi @tkoziara,

Is there any provision for outputting a reduced Solfec format database which is compatible with the Solfec viewer?

i.e. a function similar to the XDMF_EXPORT function which allows the user to output results of a subset of modelled Solfec bodies but exporting database files which are accessible by the Solfec viewer.

We find the solfec viewer much more user friendly for visualizing results than paraview.

Many thanks,

Ben

**Comment by tkoziara** [comment]
:) I'll look into this.

**Comment by tkoziara** [comment]
Hi Ben. This is most naturally done by using Glyphs on top of *_constraints.xmf data file outputted by XDMF_EXPORT. For example run twice *inp/devel/xdmf-export.py* example and then open the state file included here, [xdmftest2.zip](https://github.com/tkoziara/solfec/files/2514942/xdmftest2.zip), to see a brief demonstration (it unpacks into ParaView state fie *.pvsm). Contact forces can be visualised using a number of available Glyph shapes - I am using ordinary arrows here. I hope this helps and is still helpful.

**Comment by tkoziara** [comment]
I am looking into implementing the actual subset output. Is it important for you to be able to output subsets during simulation (in WRITE mode) - for example with a finer or a custom output time interval definition? Or is it sufficient to make it completely analogous to the XDMF_EXPORT function and only output a subset of already saved results - and hence make functional primarily in the READ mode? What's your idea?

**Comment by bencannell** [comment]
Hi @tkoziara,

Sorry I missed this. READ only mode would work just fine for us. It's for bringing visualisations back from athos.

Many thanks,

Ben

**Comment by bencannell** [comment]
Hi @tkoziara,

Using your example (and playing around with it a bit), I can't produce an equivalent figure to solfec. The main issue seems to be that the vectors aren't orientated as I expect.

See attached plots of REAC in paraview and R in Solfec at exactly the same time. I would expect them to look the same?

Paraview:
![paraview](https://user-images.githubusercontent.com/29304199/48252530-ef3fce00-e3fc-11e8-8923-c121e9dd288a.png)

Solfec:
![solfec](https://user-images.githubusercontent.com/29304199/48252603-1bf3e580-e3fd-11e8-8e34-d29750dd83e0.png)

**Comment by tkoziara** [comment]
Ben, that was a bug in XDMF export - contact reactions were exported in local coordinates; please try the latest commit.

**Comment by bencannell** [comment]
Thank you @tkoziara, that looks more sensible now!

**Comment by tkoziara** [comment]
Hi Ben, CC @stevebrasier 
The requested functionality has now been implemented as per: 
https://parmes.org/blog/solfec_export_command.html
I am closing the issue. Do feel free to reopen upon finding issues when testing on your end.
Best regards,
Tomek

**Comment by bencannell** [comment]
Thank you @tkoziara. I'll let you know how we get on with testing.
