### ISSUE TITLE
Add git changeset ID to build

### ISSUE THREAD

**Issue by stevebrasier** [parmes/solfec#80]
I think using the git changeset ID is an appropriate way to track versions on Solfec at the moment (rather than semver etc) given the way changes are happening, but it would be good to get the git ID added to the executable somehow during build.

Something like `git describe --always` is probably the right way to query git; that way you can easily move to semantic versioning by simply adding tags to the git repo, but without any tags you'll just get the changeset ID. This version information could then be printed by Solfec when it starts.

**Comment by tkoziara** [comment]
Resolved as of 1fa40c3. Running without arguments results in:
```
VERSION: 2019-01-07 1fa40c3
SYNOPSIS: solfec [-v] [-w] [-c] [-f] [-g WIDTHxHEIGHT] [-s sub-directory] [-i verbosity inteval] path
```
